labels:
  - tag_Name
  - tag_env
  - tag_component
  - instance_type
  - instance_id

secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=infra-secrets/data/prometheus token={{vault_token}} url=https://vault-internal.rdevopsb79.online:8200 validate_certs=false') }}"
